// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Account struct {
	ID           string   `json:"id"`
	Email        string   `json:"email"`
	Status       string   `json:"status"`
	Verification string   `json:"verification"`
	Roles        []string `json:"roles"`
}

type AuthPayload struct {
	AccessToken string `json:"accessToken"`
	Me          *Me    `json:"me,omitempty"`
}

type Booking struct {
	BookingID     string  `json:"bookingId"`
	EventID       string  `json:"eventId"`
	State         string  `json:"state"`
	Amount        string  `json:"amount"`
	Currency      string  `json:"currency"`
	PolicyVersion int     `json:"policyVersion"`
	ExpiresAt     string  `json:"expiresAt"`
	Version       int     `json:"version"`
	CreatedAt     string  `json:"createdAt"`
	ConfirmedAt   *string `json:"confirmedAt,omitempty"`
	CancelledAt   *string `json:"cancelledAt,omitempty"`
}

type BookingPage struct {
	Items []*Booking `json:"items"`
}

type Candidate struct {
	ParticipantA   string         `json:"participantA"`
	ParticipantB   string         `json:"participantB"`
	Eligible       bool           `json:"eligible"`
	RejectionCodes []string       `json:"rejectionCodes,omitempty"`
	Components     map[string]any `json:"components,omitempty"`
	TotalScore     *float64       `json:"totalScore,omitempty"`
	SafeReasons    []string       `json:"safeReasons,omitempty"`
}

type Checkout struct {
	Payment   *Payment       `json:"payment"`
	ActionURL string         `json:"actionUrl"`
	Fields    map[string]any `json:"fields"`
}

type CheckoutCustomerInput struct {
	BookingID string `json:"bookingId"`
	FirstName string `json:"firstName"`
	LastName  string `json:"lastName"`
	Email     string `json:"email"`
	Phone     string `json:"phone"`
	Address   string `json:"address"`
	City      string `json:"city"`
	Country   string `json:"country"`
}

type CommunityPage struct {
	Items      []*CommunityProfile `json:"items"`
	NextCursor *string             `json:"nextCursor,omitempty"`
}

type CommunityProfile struct {
	ProfileID     string   `json:"profileId"`
	Nickname      string   `json:"nickname"`
	AgeBand       string   `json:"ageBand"`
	BroadLocation string   `json:"broadLocation"`
	Bio           string   `json:"bio"`
	Interests     []string `json:"interests"`
}

type Event struct {
	EventID                string  `json:"eventId"`
	OrganizerID            *string `json:"organizerId,omitempty"`
	Name                   string  `json:"name"`
	Description            string  `json:"description"`
	VenueName              *string `json:"venueName,omitempty"`
	BroadLocation          string  `json:"broadLocation"`
	TimeZone               string  `json:"timeZone"`
	StartsAt               string  `json:"startsAt"`
	EndsAt                 string  `json:"endsAt"`
	RegistrationOpensAt    string  `json:"registrationOpensAt"`
	RegistrationClosesAt   string  `json:"registrationClosesAt"`
	Price                  string  `json:"price"`
	Currency               string  `json:"currency"`
	ConfiguredCapacity     int     `json:"configuredCapacity"`
	CapacityPolicyVersion  *int    `json:"capacityPolicyVersion,omitempty"`
	MatchingRulesetVersion string  `json:"matchingRulesetVersion"`
	Status                 string  `json:"status"`
	Version                int     `json:"version"`
}

type EventInput struct {
	OrganizerID            string `json:"organizerId"`
	Name                   string `json:"name"`
	Description            string `json:"description"`
	VenueName              string `json:"venueName"`
	BroadLocation          string `json:"broadLocation"`
	TimeZone               string `json:"timeZone"`
	StartsAt               string `json:"startsAt"`
	EndsAt                 string `json:"endsAt"`
	RegistrationOpensAt    string `json:"registrationOpensAt"`
	RegistrationClosesAt   string `json:"registrationClosesAt"`
	Price                  string `json:"price"`
	Currency               string `json:"currency"`
	ConfiguredCapacity     int    `json:"configuredCapacity"`
	MatchingRulesetVersion string `json:"matchingRulesetVersion"`
}

type EventPage struct {
	Items      []*Event `json:"items"`
	NextCursor *string  `json:"nextCursor,omitempty"`
	Limit      int      `json:"limit"`
}

type MatchingPreferences struct {
	MinAge       int      `json:"minAge"`
	MaxAge       int      `json:"maxAge"`
	Intentions   []string `json:"intentions"`
	InterestedIn []string `json:"interestedIn"`
	Languages    []string `json:"languages"`
	DealBreakers []string `json:"dealBreakers"`
}

type MatchingRun struct {
	RunID             string       `json:"runId"`
	EventID           string       `json:"eventId"`
	RunVersion        int          `json:"runVersion"`
	Version           int          `json:"version"`
	Status            string       `json:"status"`
	RulesetVersion    string       `json:"rulesetVersion"`
	OptimizerVersion  string       `json:"optimizerVersion"`
	TieBreakPolicy    string       `json:"tieBreakPolicy"`
	ParticipantCount  int          `json:"participantCount"`
	EligiblePairCount int          `json:"eligiblePairCount"`
	CreatedBy         string       `json:"createdBy"`
	CreatedAt         string       `json:"createdAt"`
	UpdatedAt         string       `json:"updatedAt"`
	Suggestions       []*Pairing   `json:"suggestions,omitempty"`
	Selections        []*Pairing   `json:"selections,omitempty"`
	Unmatched         []*Unmatched `json:"unmatched,omitempty"`
	Candidates        []*Candidate `json:"candidates,omitempty"`
}

type MatchingRunPage struct {
	Items []*MatchingRun `json:"items"`
}

type Me struct {
	Account     *Account             `json:"account"`
	Profile     *Profile             `json:"profile"`
	Preferences *MatchingPreferences `json:"preferences,omitempty"`
}

type Mutation struct {
}

type Notification struct {
	NotificationID  string  `json:"notificationId"`
	SourceEventType string  `json:"sourceEventType"`
	Category        string  `json:"category"`
	Title           string  `json:"title"`
	Message         string  `json:"message"`
	ActionPath      string  `json:"actionPath"`
	ReadAt          *string `json:"readAt,omitempty"`
	CreatedAt       string  `json:"createdAt"`
}

type NotificationPage struct {
	Items       []*Notification `json:"items"`
	NextCursor  *string         `json:"nextCursor,omitempty"`
	UnreadCount int             `json:"unreadCount"`
}

type OperationResult struct {
	Success bool `json:"success"`
}

type Pairing struct {
	PairingID        *string  `json:"pairingId,omitempty"`
	ParticipantA     string   `json:"participantA"`
	ParticipantB     string   `json:"participantB"`
	ParticipantACode *string  `json:"participantACode,omitempty"`
	ParticipantBCode *string  `json:"participantBCode,omitempty"`
	Score            float64  `json:"score"`
	SafeReasons      []string `json:"safeReasons"`
	Source           *string  `json:"source,omitempty"`
}

type PairingOverrideInput struct {
	RemoveSelectionID string `json:"removeSelectionId"`
	ParticipantA      string `json:"participantA"`
	ParticipantB      string `json:"participantB"`
	Reason            string `json:"reason"`
}

type Payment struct {
	PaymentID   string  `json:"paymentId"`
	BookingID   string  `json:"bookingId"`
	OrderID     string  `json:"orderId"`
	Amount      string  `json:"amount"`
	Currency    string  `json:"currency"`
	Provider    string  `json:"provider"`
	State       string  `json:"state"`
	Version     int     `json:"version"`
	CreatedAt   string  `json:"createdAt"`
	UpdatedAt   string  `json:"updatedAt"`
	CompletedAt *string `json:"completedAt,omitempty"`
}

type PreferencesInput struct {
	MinAge       *int     `json:"minAge,omitempty"`
	MaxAge       *int     `json:"maxAge,omitempty"`
	Intentions   []string `json:"intentions,omitempty"`
	InterestedIn []string `json:"interestedIn,omitempty"`
	Languages    []string `json:"languages,omitempty"`
	DealBreakers []string `json:"dealBreakers,omitempty"`
}

type Profile struct {
	AccountID     string   `json:"accountID"`
	Nickname      string   `json:"nickname"`
	DateOfBirth   string   `json:"dateOfBirth"`
	BroadLocation string   `json:"broadLocation"`
	Bio           string   `json:"bio"`
	Visibility    string   `json:"visibility"`
	Approval      string   `json:"approval"`
	Interests     []string `json:"interests"`
	Version       int      `json:"version"`
}

type ProfileInput struct {
	Nickname        *string  `json:"nickname,omitempty"`
	BroadLocation   *string  `json:"broadLocation,omitempty"`
	Bio             *string  `json:"bio,omitempty"`
	Visibility      *string  `json:"visibility,omitempty"`
	Interests       []string `json:"interests,omitempty"`
	ExpectedVersion int      `json:"expectedVersion"`
}

type Query struct {
}

type RegisterInput struct {
	Email          string `json:"email"`
	Password       string `json:"password"`
	Nickname       string `json:"nickname"`
	DateOfBirth    string `json:"dateOfBirth"`
	ConsentVersion string `json:"consentVersion"`
}

type RegistrationPayload struct {
	Me                *Me     `json:"me"`
	VerificationToken *string `json:"verificationToken,omitempty"`
}

type Unmatched struct {
	ParticipantID   string  `json:"participantId"`
	ParticipantCode *string `json:"participantCode,omitempty"`
	Reason          string  `json:"reason"`
}

type UnreadCount struct {
	UnreadCount int `json:"unreadCount"`
}

type UpdatedCount struct {
	UpdatedCount int `json:"updatedCount"`
}
