import { useState } from 'react'
import { Link } from '@tanstack/react-router'
import { useForm } from '@tanstack/react-form'
import { z } from 'zod'
import { ApiProblem, register, verifyEmail } from '../lib/account-api'

const schema=z.object({email:z.email(),password:z.string().min(12),nickname:z.string().min(2).max(40),dateOfBirth:z.string().min(10),consent:z.boolean().refine(Boolean)})
export function RegisterPage(){const [message,setMessage]=useState('');const [token,setToken]=useState('');const form=useForm({defaultValues:{email:'',password:'',nickname:'',dateOfBirth:'',consent:false},onSubmit:async({value})=>{const parsed=schema.safeParse(value);if(!parsed.success){setMessage('Check every field and use a password of at least 12 characters.');return}try{const result=await register(toRegistrationRequest(value));setToken(result.verificationToken??'');setMessage('Your private profile was created. Verify your email before signing in.')}catch(error){setMessage((error as ApiProblem).detail??'Registration failed.')}}});return <AccountShell title="Create your private profile" intro="Start privately. Nothing appears in the community until you choose Community visibility and a moderator approves it."><form onSubmit={e=>{e.preventDefault();void form.handleSubmit()}}><Field form={form} name="email" label="Email" type="email"/><Field form={form} name="password" label="Password (12+ characters)" type="password"/><Field form={form} name="nickname" label="Nickname"/><Field form={form} name="dateOfBirth" label="Date of birth" type="date"/><form.Field name="consent">{field=><label className="check"><input type="checkbox" checked={field.state.value} onChange={e=>field.handleChange(e.target.checked)}/> I am 18+ and accept the privacy terms.</label>}</form.Field><button className="button" type="submit">Create account</button></form>{message&&<p className="form-message" role="status">{message}</p>}{token&&<button className="text-action" onClick={async()=>{try{await verifyEmail(token);setMessage('Email verified. You can now sign in.')}catch(error){setMessage((error as ApiProblem).detail)}}}>Verify development account</button>}<p>Already registered? <Link to="/login">Sign in</Link></p></AccountShell>}

type FormShape={email:string;password:string;nickname:string;dateOfBirth:string;consent:boolean}
export function toRegistrationRequest(value:FormShape){return {email:value.email,password:value.password,nickname:value.nickname,dateOfBirth:value.dateOfBirth,consentVersion:'privacy-2026-08'}}
function Field({form,name,label,type='text'}:{form:any;name:keyof FormShape;label:string;type?:string}){return <form.Field name={name}>{(field:any)=><label>{label}<input type={type} value={field.state.value as string} onBlur={field.handleBlur} onChange={e=>field.handleChange(e.target.value)}/></label>}</form.Field>}
export function AccountShell({title,intro,children}:{title:string;intro:string;children:React.ReactNode}){return <main className="account-page"><section className="account-panel"><Link className="account-brand" to="/">MatchMate</Link><p className="eyebrow">Member account</p><h1>{title}</h1><p className="account-intro">{intro}</p>{children}</section><aside><p>Privacy by default</p><strong>Your email, date of birth, preferences, and deal-breakers are never part of the community profile.</strong></aside></main>}
