import {useState} from 'react'
import {useMutation,useQuery,useQueryClient} from '@tanstack/react-query'
import {Link} from '@tanstack/react-router'
import {createBooking,findResumableBooking,initiatePayment,listBookings,submitCheckout,type Booking} from '../lib/booking-api'
import type {PublicEvent} from '../lib/event-api'

export function BookingPurchasePanel({eventId,isOpen,paymentOptions}:{eventId:string;isOpen:boolean;paymentOptions:PublicEvent['paymentOptions']}){
  const [booking,setBooking]=useState<Booking|null>(null)
  const [method,setMethod]=useState<'ONLINE'|'AT_VENUE'>(paymentOptions==='ONLINE'?'ONLINE':'AT_VENUE')
  const [message,setMessage]=useState('')
  const client=useQueryClient()
  const bookings=useQuery({queryKey:['bookings'],queryFn:listBookings,retry:false,staleTime:5000})
  const existing=bookings.data?.items.find(item=>item.eventId===eventId&&item.state==='CONFIRMED')??findResumableBooking(bookings.data?.items,eventId)
  const activeBooking=booking??existing
  const reserve=useMutation({mutationFn:()=>createBooking(eventId,crypto.randomUUID(),method),onSuccess:(value)=>{setBooking(value);setMessage(value.paymentMethod==='AT_VENUE'?'Seat confirmed. Pay the ticket price at the event entrance.':'Your seat is held. Complete checkout before the timer expires.');void client.invalidateQueries({queryKey:['bookings']})},onError:()=>{setMessage('We could not reserve this seat. Sign in, check eligibility, or try again.');void client.invalidateQueries({queryKey:['bookings']})}})
  const checkout=useMutation({mutationFn:(input:{firstName:string;lastName:string;email:string;phone:string;address:string;city:string;country:string})=>initiatePayment({bookingId:activeBooking!.bookingId,...input}),onSuccess:submitCheckout,onError:()=>setMessage('Checkout could not start. Your hold remains visible in My bookings.')})
  if(!isOpen&&!activeBooking)return <p className="purchase-message">Registration is not currently open.</p>
  if(bookings.isPending&&!booking)return <button className="button event-detail-action" type="button" disabled>Checking your booking…</button>
  if(!activeBooking)return <div className="purchase-flow">{paymentOptions==='BOTH'&&<label>Choose how to pay<select value={method} onChange={event=>setMethod(event.target.value as 'ONLINE'|'AT_VENUE')}><option value="AT_VENUE">Pay at the venue</option><option value="ONLINE">Pay online with PayHere</option></select></label>}<button className="button event-detail-action" type="button" disabled={reserve.isPending} onClick={()=>reserve.mutate()}>{reserve.isPending?'Reserving…':method==='AT_VENUE'?'Reserve now · pay at venue':'Reserve a seat'} <b aria-hidden="true">→</b></button>{message&&<p className="purchase-message" role="status">{message} <Link to="/login">Sign in</Link></p>}</div>
  if(activeBooking.state==='CONFIRMED')return <div className="purchase-flow"><p className="purchase-message" role="status">Seat confirmed. {activeBooking.paymentMethod==='AT_VENUE'?`Pay ${activeBooking.currency} ${activeBooking.amount} at the event entrance.`:'Online payment confirmed.'}</p><p className="hold-reference">Booking reference <strong>{activeBooking.bookingId}</strong></p><Link to="/app/bookings">View my bookings</Link></div>
  const checkoutMessage=message||'Your existing seat hold is ready. Complete payment before it expires.'
  return <div className="purchase-flow"><p className="purchase-message" role="status">{checkoutMessage}</p><p className="hold-reference">Hold expires <strong>{new Date(activeBooking.expiresAt).toLocaleTimeString('en-LK',{hour:'2-digit',minute:'2-digit'})}</strong></p><form onSubmit={(event)=>{event.preventDefault();const data=new FormData(event.currentTarget);checkout.mutate({firstName:String(data.get('firstName')),lastName:String(data.get('lastName')),email:String(data.get('email')),phone:String(data.get('phone')),address:String(data.get('address')),city:String(data.get('city')),country:String(data.get('country'))})}}><div className="purchase-name-row"><label>First name<input name="firstName" autoComplete="given-name" required /></label><label>Last name<input name="lastName" autoComplete="family-name" required /></label></div><label>Email<input name="email" type="email" autoComplete="email" required /></label><label>Phone<input name="phone" type="tel" autoComplete="tel" required /></label><label>Billing address<input name="address" autoComplete="street-address" required /></label><div className="purchase-name-row"><label>City<input name="city" autoComplete="address-level2" required /></label><label>Country<input name="country" autoComplete="country-name" defaultValue="Sri Lanka" required /></label></div><button className="button event-detail-action" disabled={checkout.isPending}>{checkout.isPending?'Opening PayHere…':'Pay '+activeBooking.currency+' '+activeBooking.amount}</button></form><p className="event-detail-ticket-note">PayHere receives these checkout details transiently. MatchMate confirms payment only after a verified server callback.</p></div>
}
