import {useState} from 'react'
import {useMutation} from '@tanstack/react-query'
import {Link} from '@tanstack/react-router'
import {createBooking,initiatePayment,submitCheckout,type Booking} from '../lib/booking-api'

export function BookingPurchasePanel({eventId,isOpen}:{eventId:string;isOpen:boolean}){
  const [booking,setBooking]=useState<Booking|null>(null)
  const [message,setMessage]=useState('')
  const hold=useMutation({mutationFn:()=>createBooking(eventId),onSuccess:(value)=>{setBooking(value);setMessage('Your seat is held. Complete checkout before the timer expires.')},onError:()=>setMessage('We could not reserve this seat. Sign in, check eligibility, or try again.')})
  const checkout=useMutation({mutationFn:(input:{firstName:string;lastName:string;email:string;phone:string;address:string;city:string;country:string})=>initiatePayment({bookingId:booking!.bookingId,...input}),onSuccess:submitCheckout,onError:()=>setMessage('Checkout could not start. Your hold remains visible in My bookings.')})
  if(!isOpen)return <p className="purchase-message">Registration is not currently open.</p>
  if(!booking)return <><button className="button event-detail-action" type="button" disabled={hold.isPending} onClick={()=>hold.mutate()}>{hold.isPending?'Reserving…':'Reserve a seat'} <b aria-hidden="true">→</b></button>{message&&<p className="purchase-message" role="status">{message} <Link to="/login">Sign in</Link></p>}</>
  return <div className="purchase-flow"><p className="purchase-message" role="status">{message}</p><p className="hold-reference">Hold expires <strong>{new Date(booking.expiresAt).toLocaleTimeString('en-LK',{hour:'2-digit',minute:'2-digit'})}</strong></p><form onSubmit={(event)=>{event.preventDefault();const data=new FormData(event.currentTarget);checkout.mutate({firstName:String(data.get('firstName')),lastName:String(data.get('lastName')),email:String(data.get('email')),phone:String(data.get('phone')),address:String(data.get('address')),city:String(data.get('city')),country:String(data.get('country'))})}}><div className="purchase-name-row"><label>First name<input name="firstName" autoComplete="given-name" required /></label><label>Last name<input name="lastName" autoComplete="family-name" required /></label></div><label>Email<input name="email" type="email" autoComplete="email" required /></label><label>Phone<input name="phone" type="tel" autoComplete="tel" required /></label><label>Billing address<input name="address" autoComplete="street-address" required /></label><div className="purchase-name-row"><label>City<input name="city" autoComplete="address-level2" required /></label><label>Country<input name="country" autoComplete="country-name" defaultValue="Sri Lanka" required /></label></div><button className="button event-detail-action" disabled={checkout.isPending}>{checkout.isPending?'Opening PayHere…':`Pay ${booking.currency} ${booking.amount}`}</button></form><p className="event-detail-ticket-note">PayHere receives these checkout details transiently. MatchMate confirms payment only after a verified server callback.</p></div>
}
