import {graphqlClient as client,type ApiProblem as GraphQLProblem} from '../../../web/src/lib/account-api'
export type Problem=GraphQLProblem
export type AdminAccount={id:string;email?:string;roles:string[]}
export type EventStatus='DRAFT'|'PUBLISHED'|'REGISTRATION_OPEN'|'REGISTRATION_CLOSED'|'CANCELLED'
export type ManagedEvent={eventId:string;organizerId:string;name:string;description:string;venueName:string;broadLocation:string;timeZone:string;startsAt:string;endsAt:string;registrationOpensAt:string;registrationClosesAt:string;price:string;currency:string;configuredCapacity:number;capacityPolicyVersion:number;matchingRulesetVersion:string;status:EventStatus;version:number}
export type EventInput=Omit<ManagedEvent,'eventId'|'status'|'version'|'capacityPolicyVersion'>
export type Pairing={pairingId?:string;participantA:string;participantB:string;participantACode?:string;participantBCode?:string;score:number;safeReasons:string[];source?:'ALGORITHM'|'OVERRIDE'}
export type Candidate={participantA:string;participantB:string;eligible:boolean;rejectionCodes?:string[];components?:Record<string,number>;totalScore?:number;safeReasons?:string[]}
export type Unmatched={participantId:string;participantCode?:string;reason:string}
export type MatchingRun={runId:string;eventId:string;runVersion:number;version:number;status:'GENERATED'|'UNDER_REVIEW'|'LOCKED'|'PUBLISHED'|'INVALIDATED';rulesetVersion:string;optimizerVersion:string;tieBreakPolicy:string;participantCount:number;eligiblePairCount:number;createdBy:string;createdAt:string;updatedAt:string;suggestions?:Pairing[];selections?:Pairing[];unmatched?:Unmatched[];candidates?:Candidate[]}

const accountFields='id email roles'
const eventFields='eventId organizerId name description venueName broadLocation timeZone startsAt endsAt registrationOpensAt registrationClosesAt price currency configuredCapacity capacityPolicyVersion matchingRulesetVersion status version'
const pairingFields='pairingId participantA participantB participantACode participantBCode score safeReasons source'
const runFields=`runId eventId runVersion version status rulesetVersion optimizerVersion tieBreakPolicy participantCount eligiblePairCount createdBy createdAt updatedAt suggestions{${pairingFields}} selections{${pairingFields}} unmatched{participantId participantCode reason} candidates{participantA participantB eligible rejectionCodes components totalScore safeReasons}`

function requireAdmin(account:AdminAccount){if(!account.roles.includes('admin')){client.clearToken();throw {code:'ADMIN_ROLE_REQUIRED',detail:'This workspace is restricted to MatchMate administrators.',status:403} satisfies Problem}return account}
export async function login(email:string,password:string){const data=await client.execute<{login:{accessToken:string;me:{account:AdminAccount}}}>(`mutation AdminLogin($email:String!,$password:String!){login(email:$email,password:$password){accessToken me{account{${accountFields}}}}}`,{email,password},false);client.setToken(data.login.accessToken);return requireAdmin(data.login.me.account)}
export async function refresh(){return client.refresh()}
async function currentAccount(){const data=await client.execute<{me:{account:AdminAccount}}>(`query AdminMe{me{account{${accountFields}}}}`);return requireAdmin(data.me.account)}
export async function restoreAdminSession(){try{return await currentAccount()}catch{return undefined}}
export async function logout(){try{await client.execute(`mutation Logout{logout{success}}`,{},false)}finally{client.clearToken()}}
export async function listManagedEvents(){const data=await client.execute<{managedEvents:{items:ManagedEvent[];nextCursor?:string;limit:number}}>(`query ManagedEvents{managedEvents(limit:100){items{${eventFields}} nextCursor limit}}`);return data.managedEvents}
export async function createEvent(input:EventInput){const data=await client.execute<{createEvent:ManagedEvent}>(`mutation CreateEvent($input:EventInput!){createEvent(input:$input){${eventFields}}}`,{input});return data.createEvent}
export async function updateEvent(eventId:string,input:EventInput,expectedVersion:number){const data=await client.execute<{updateEvent:ManagedEvent}>(`mutation UpdateEvent($eventId:ID!,$input:EventInput!,$expectedVersion:Int!){updateEvent(eventId:$eventId,input:$input,expectedVersion:$expectedVersion){${eventFields}}}`,{eventId,input,expectedVersion});return data.updateEvent}
export async function transitionEvent(event:ManagedEvent,action:'publish'|'open-registration'|'close-registration'|'cancel',reason=''){const data=await client.execute<{transitionEvent:ManagedEvent}>(`mutation TransitionEvent($eventId:ID!,$action:String!,$expectedVersion:Int!,$reason:String){transitionEvent(eventId:$eventId,action:$action,expectedVersion:$expectedVersion,reason:$reason){${eventFields}}}`,{eventId:event.eventId,action,expectedVersion:event.version,reason:reason||null});return data.transitionEvent}
const key=(prefix:string)=>`${prefix}-${crypto.randomUUID()}`
export async function listMatchingRuns(eventId:string){const data=await client.execute<{matchingRuns:{items:MatchingRun[]}}>(`query MatchingRuns($eventId:ID!){matchingRuns(eventId:$eventId){items{${runFields}}}}`,{eventId});return data.matchingRuns}
export async function getMatchingRun(runId:string){const data=await client.execute<{matchingRun:MatchingRun}>(`query MatchingRun($runId:ID!){matchingRun(runId:$runId){${runFields}}}`,{runId});return data.matchingRun}
export async function generateMatchingRun(eventId:string){const data=await client.execute<{generateMatchingRun:MatchingRun}>(`mutation GenerateRun($eventId:ID!,$key:String!){generateMatchingRun(eventId:$eventId,idempotencyKey:$key){${runFields}}}`,{eventId,key:key('generate')});return data.generateMatchingRun}
export async function reviewMatchingRun(run:MatchingRun){const data=await client.execute<{reviewMatchingRun:MatchingRun}>(`mutation ReviewRun($runId:ID!,$version:Int!){reviewMatchingRun(runId:$runId,expectedVersion:$version){${runFields}}}`,{runId:run.runId,version:run.version});return data.reviewMatchingRun}
export async function lockMatchingRun(run:MatchingRun){const data=await client.execute<{lockMatchingRun:MatchingRun}>(`mutation LockRun($runId:ID!,$version:Int!,$key:String!){lockMatchingRun(runId:$runId,expectedVersion:$version,idempotencyKey:$key){${runFields}}}`,{runId:run.runId,version:run.version,key:key('lock')});return data.lockMatchingRun}
export async function publishMatchingRun(run:MatchingRun){const data=await client.execute<{publishMatchingRun:MatchingRun}>(`mutation PublishRun($runId:ID!,$version:Int!,$key:String!){publishMatchingRun(runId:$runId,expectedVersion:$version,idempotencyKey:$key){${runFields}}}`,{runId:run.runId,version:run.version,key:key('publish')});return data.publishMatchingRun}
export async function overridePairing(run:MatchingRun,input:{removeSelectionId:string;participantA:string;participantB:string;reason:string}){const data=await client.execute<{overridePairing:MatchingRun}>(`mutation Override($runId:ID!,$version:Int!,$input:PairingOverrideInput!,$key:String!){overridePairing(runId:$runId,expectedVersion:$version,input:$input,idempotencyKey:$key){${runFields}}}`,{runId:run.runId,version:run.version,input,key:key('override')});return data.overridePairing}
