const accountBase=import.meta.env.VITE_ACCOUNT_API_URL??'http://localhost:8081/api/v1';const eventBase=import.meta.env.VITE_EVENT_API_URL??'http://localhost:8082/api/v1';let token=''
export type Problem=Error&{code:string;detail:string;fieldErrors?:Record<string,string>}
export type EventStatus='DRAFT'|'PUBLISHED'|'REGISTRATION_OPEN'|'REGISTRATION_CLOSED'|'CANCELLED'
export type ManagedEvent={eventId:string;organizerId:string;name:string;description:string;venueName:string;broadLocation:string;timeZone:string;startsAt:string;endsAt:string;registrationOpensAt:string;registrationClosesAt:string;price:string;currency:string;configuredCapacity:number;capacityPolicyVersion:number;matchingRulesetVersion:string;status:EventStatus;version:number}
export type EventInput=Omit<ManagedEvent,'eventId'|'status'|'version'|'capacityPolicyVersion'>
async function call<T>(base:string,path:string,init:RequestInit={}):Promise<T>{const headers=new Headers(init.headers);headers.set('Content-Type','application/json');if(token)headers.set('Authorization',`Bearer ${token}`);const response=await fetch(base+path,{...init,headers,credentials:'include'});if(!response.ok)throw await response.json() as Problem;return response.status===204?undefined as T:response.json() as Promise<T>}
export async function login(email:string,password:string){const auth=await call<{accessToken:string}>(accountBase,'/auth/login',{method:'POST',body:JSON.stringify({email,password})});token=auth.accessToken;const me=await call<{account:{id:string;roles:string[]}}>(accountBase,'/users/me');if(!me.account.roles.some(role=>role==='organizer'||role==='admin')){token='';throw Object.assign(new Error('This account is not assigned an organizer or admin role.'),{code:'ORGANIZER_ROLE_REQUIRED',detail:'This account is not assigned an organizer or admin role.'}) satisfies Problem}return me.account}
export const listManaged=()=>call<{items:ManagedEvent[];nextCursor?:string;limit:number}>(eventBase,'/organizer/events?limit=100')
export const createEvent=(input:EventInput)=>call<ManagedEvent>(eventBase,'/events',{method:'POST',body:JSON.stringify(input)})
export const updateEvent=(eventId:string,input:EventInput,expectedVersion:number)=>call<ManagedEvent>(eventBase,`/events/${eventId}`,{method:'PATCH',body:JSON.stringify({...input,expectedVersion})})
export const transition=(event:ManagedEvent,action:'publish'|'open-registration'|'close-registration'|'cancel',reason='')=>call<ManagedEvent>(eventBase,`/events/${event.eventId}/${action}`,{method:'POST',body:JSON.stringify({expectedVersion:event.version,reason})})
