CREATE TABLE moderation_case(case_id uuid PRIMARY KEY,status text NOT NULL CHECK(status IN('OPEN','TRIAGED','INVESTIGATING','ACTIONED','DISMISSED')),severity text NOT NULL CHECK(severity IN('LOW','MEDIUM','HIGH','CRITICAL')),assignee_id uuid,sla_at timestamptz,version bigint NOT NULL DEFAULT 1,created_at timestamptz NOT NULL,updated_at timestamptz NOT NULL);
CREATE TABLE report(report_id uuid PRIMARY KEY,case_id uuid NOT NULL REFERENCES moderation_case(case_id),reporter_id uuid NOT NULL,reporter_role text NOT NULL,target_type text NOT NULL CHECK(target_type IN('ACCOUNT','PROFILE','EVENT','BOOKING','PAIRING')),target_id uuid NOT NULL,event_id uuid,category text NOT NULL CHECK(category IN('HARASSMENT','SAFETY','IMPERSONATION','CONTACT_SHARING','INAPPROPRIATE_CONTENT','FRAUD','OTHER')),description text NOT NULL CHECK(length(description) BETWEEN 10 AND 2000),dedupe_hash bytea NOT NULL,status text NOT NULL CHECK(status IN('OPEN','TRIAGED','INVESTIGATING','ACTIONED','DISMISSED')),created_at timestamptz NOT NULL,updated_at timestamptz NOT NULL,UNIQUE(reporter_id,dedupe_hash));
CREATE TABLE evidence_reference(evidence_id uuid PRIMARY KEY,report_id uuid NOT NULL REFERENCES report(report_id),reference text NOT NULL,media_type text NOT NULL,sha256 char(64) NOT NULL,retain_until timestamptz,legal_hold boolean NOT NULL DEFAULT false,created_at timestamptz NOT NULL);
CREATE TABLE moderation_action(action_id uuid PRIMARY KEY,case_id uuid NOT NULL REFERENCES moderation_case(case_id),target_type text NOT NULL,target_id uuid NOT NULL,action_class text NOT NULL CHECK(action_class IN('CONTENT_HIDE','PROFILE_RESTRICTION','EVENT_EXCLUSION','ACCOUNT_SUSPENSION','MATCHMAKING_EXCLUSION','PAIRING_INVALIDATION','REVEAL_PREVENTION')),scope text NOT NULL,reason text NOT NULL,actor_id uuid NOT NULL,version bigint NOT NULL,effective_at timestamptz NOT NULL,expires_at timestamptz,state text NOT NULL CHECK(state IN('ACTIVE','EXPIRED','REVERSED')),created_at timestamptz NOT NULL,UNIQUE(target_type,target_id,action_class,scope,version));
CREATE UNIQUE INDEX moderation_action_active_idx ON moderation_action(target_type,target_id,action_class,scope) WHERE state='ACTIVE';
CREATE TABLE appeal(appeal_id uuid PRIMARY KEY,action_id uuid NOT NULL REFERENCES moderation_action(action_id),appellant_id uuid NOT NULL,reason text NOT NULL CHECK(length(reason) BETWEEN 10 AND 1000),state text NOT NULL CHECK(state IN('APPEALED','UPHELD','REVERSED')),decision_actor_id uuid,decision_reason text,created_at timestamptz NOT NULL,decided_at timestamptz,UNIQUE(action_id,appellant_id));
CREATE TABLE moderation_audit(audit_id uuid PRIMARY KEY,case_id uuid,actor_id uuid NOT NULL,operation text NOT NULL,target_type text NOT NULL,target_id text NOT NULL,reason text NOT NULL,metadata jsonb NOT NULL DEFAULT '{}',correlation_id text NOT NULL,occurred_at timestamptz NOT NULL);
CREATE TABLE outbox(event_id uuid PRIMARY KEY,event_type text NOT NULL,schema_version integer NOT NULL,occurred_at timestamptz NOT NULL,aggregate_id text NOT NULL,correlation_id text NOT NULL,causation_id text NOT NULL DEFAULT '',actor_id text NOT NULL,routing_key text NOT NULL,payload jsonb NOT NULL,claimed_at timestamptz,published_at timestamptz,attempts integer NOT NULL DEFAULT 0);
CREATE INDEX report_owner_created_idx ON report(reporter_id,created_at DESC,report_id DESC);CREATE INDEX case_queue_idx ON moderation_case(status,severity,updated_at DESC);CREATE INDEX action_expiry_idx ON moderation_action(expires_at) WHERE state='ACTIVE' AND expires_at IS NOT NULL;CREATE INDEX outbox_unpublished_idx ON outbox(occurred_at) WHERE published_at IS NULL;
