package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.93

import (
	"context"
	"errors"
	"net/http"

	"github.com/gehan-malshan/matchmate/graphql-gateway/graph/model"
)

// Register is the resolver for the register field.
func (r *mutationResolver) Register(ctx context.Context, input model.RegisterInput) (*model.RegistrationPayload, error) {
	var result model.RegistrationPayload
	err := r.Upstream.Do(ctx, r.Upstream.Services.Account, "/auth/register", http.MethodPost, input, &result, nil)
	return &result, err
}

// VerifyEmail is the resolver for the verifyEmail field.
func (r *mutationResolver) VerifyEmail(ctx context.Context, token string) (*model.OperationResult, error) {
	err := r.Upstream.Do(ctx, r.Upstream.Services.Account, "/auth/verify-email", http.MethodPost, map[string]string{"token": token}, nil, nil)
	return &model.OperationResult{Success: err == nil}, err
}

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, email string, password string) (*model.AuthPayload, error) {
	var auth model.AuthPayload
	if err := r.Upstream.Do(ctx, r.Upstream.Services.Account, "/auth/login", http.MethodPost, map[string]string{"email": email, "password": password}, &auth, nil); err != nil {
		return nil, err
	}
	var me model.Me
	if err := r.Upstream.Do(ctx, r.Upstream.Services.Account, "/users/me", http.MethodGet, nil, &me, map[string]string{"Authorization": "Bearer " + auth.AccessToken}); err != nil {
		return nil, err
	}
	auth.Me = &me
	return &auth, nil
}

// RefreshSession is the resolver for the refreshSession field.
func (r *mutationResolver) RefreshSession(ctx context.Context) (*model.AuthPayload, error) {
	var auth model.AuthPayload
	if err := r.Upstream.Do(ctx, r.Upstream.Services.Account, "/auth/refresh", http.MethodPost, nil, &auth, nil); err != nil {
		return nil, err
	}
	var me model.Me
	if err := r.Upstream.Do(ctx, r.Upstream.Services.Account, "/users/me", http.MethodGet, nil, &me, map[string]string{"Authorization": "Bearer " + auth.AccessToken}); err != nil {
		return nil, err
	}
	auth.Me = &me
	return &auth, nil
}

// Logout is the resolver for the logout field.
func (r *mutationResolver) Logout(ctx context.Context) (*model.OperationResult, error) {
	err := r.Upstream.Do(ctx, r.Upstream.Services.Account, "/auth/logout", http.MethodPost, nil, nil, nil)
	return &model.OperationResult{Success: err == nil}, err
}

// UpdateProfile is the resolver for the updateProfile field.
func (r *mutationResolver) UpdateProfile(ctx context.Context, input model.ProfileInput) (*model.Profile, error) {
	var result model.Profile
	err := r.Upstream.Do(ctx, r.Upstream.Services.Account, "/users/me/profile", http.MethodPatch, input, &result, nil)
	return &result, err
}

// UpdatePreferences is the resolver for the updatePreferences field.
func (r *mutationResolver) UpdatePreferences(ctx context.Context, input model.PreferencesInput) (*model.MatchingPreferences, error) {
	var result model.MatchingPreferences
	err := r.Upstream.Do(ctx, r.Upstream.Services.Account, "/users/me/matching-preferences", http.MethodPut, input, &result, nil)
	return &result, err
}

// BlockMember is the resolver for the blockMember field.
func (r *mutationResolver) BlockMember(ctx context.Context, accountID string) (*model.OperationResult, error) {
	err := r.Upstream.Do(ctx, r.Upstream.Services.Account, "/users/me/blocks", http.MethodPost, map[string]string{"accountId": accountID}, nil, nil)
	return &model.OperationResult{Success: err == nil}, err
}

// CreateBooking is the resolver for the createBooking field.
func (r *mutationResolver) CreateBooking(ctx context.Context, eventID string, idempotencyKey string) (*model.Booking, error) {
	var result model.Booking
	err := r.Upstream.Do(ctx, r.Upstream.Services.Booking, "/bookings", http.MethodPost, map[string]string{"eventId": eventID}, &result, map[string]string{"Idempotency-Key": idempotencyKey})
	return &result, err
}

// CancelBooking is the resolver for the cancelBooking field.
func (r *mutationResolver) CancelBooking(ctx context.Context, bookingID string, idempotencyKey string) (*model.Booking, error) {
	var result model.Booking
	err := r.Upstream.Do(ctx, r.Upstream.Services.Booking, "/bookings/"+escape(bookingID)+"/cancel", http.MethodPost, nil, &result, map[string]string{"Idempotency-Key": idempotencyKey})
	return &result, err
}

// InitiatePayment is the resolver for the initiatePayment field.
func (r *mutationResolver) InitiatePayment(ctx context.Context, input model.CheckoutCustomerInput, idempotencyKey string) (*model.Checkout, error) {
	var result model.Checkout
	err := r.Upstream.Do(ctx, r.Upstream.Services.Payment, "/payments/initiate", http.MethodPost, input, &result, map[string]string{"Idempotency-Key": idempotencyKey})
	return &result, err
}

// MarkNotificationRead is the resolver for the markNotificationRead field.
func (r *mutationResolver) MarkNotificationRead(ctx context.Context, notificationID string) (*model.OperationResult, error) {
	err := r.Upstream.Do(ctx, r.Upstream.Services.Notification, "/notifications/"+escape(notificationID)+"/read", http.MethodPatch, nil, nil, nil)
	return &model.OperationResult{Success: err == nil}, err
}

// MarkAllNotificationsRead is the resolver for the markAllNotificationsRead field.
func (r *mutationResolver) MarkAllNotificationsRead(ctx context.Context) (*model.UpdatedCount, error) {
	var result model.UpdatedCount
	err := r.Upstream.Do(ctx, r.Upstream.Services.Notification, "/notifications/read-all", http.MethodPost, nil, &result, nil)
	return &result, err
}

// CreateEvent is the resolver for the createEvent field.
func (r *mutationResolver) CreateEvent(ctx context.Context, input model.EventInput) (*model.Event, error) {
	if _, err := r.Upstream.RequireAdmin(ctx); err != nil {
		return nil, err
	}
	var result model.Event
	err := r.Upstream.Do(ctx, r.Upstream.Services.Event, "/events", http.MethodPost, input, &result, nil)
	return &result, err
}

// UpdateEvent is the resolver for the updateEvent field.
func (r *mutationResolver) UpdateEvent(ctx context.Context, eventID string, input model.EventInput, expectedVersion int) (*model.Event, error) {
	if _, err := r.Upstream.RequireAdmin(ctx); err != nil {
		return nil, err
	}
	body := map[string]any{
		"organizerId": input.OrganizerID, "name": input.Name, "description": input.Description, "venueName": input.VenueName,
		"broadLocation": input.BroadLocation, "timeZone": input.TimeZone, "startsAt": input.StartsAt, "endsAt": input.EndsAt,
		"registrationOpensAt": input.RegistrationOpensAt, "registrationClosesAt": input.RegistrationClosesAt, "price": input.Price,
		"currency": input.Currency, "configuredCapacity": input.ConfiguredCapacity, "matchingRulesetVersion": input.MatchingRulesetVersion,
		"expectedVersion": expectedVersion,
	}
	var result model.Event
	err := r.Upstream.Do(ctx, r.Upstream.Services.Event, "/events/"+escape(eventID), http.MethodPatch, body, &result, nil)
	return &result, err
}

// TransitionEvent is the resolver for the transitionEvent field.
func (r *mutationResolver) TransitionEvent(ctx context.Context, eventID string, action string, expectedVersion int, reason *string) (*model.Event, error) {
	if _, err := r.Upstream.RequireAdmin(ctx); err != nil {
		return nil, err
	}
	allowed := map[string]bool{"publish": true, "open-registration": true, "close-registration": true, "cancel": true}
	if !allowed[action] {
		return nil, errors.New("unsupported event transition")
	}
	body := map[string]any{"expectedVersion": expectedVersion}
	if reason != nil {
		body["reason"] = *reason
	}
	var result model.Event
	err := r.Upstream.Do(ctx, r.Upstream.Services.Event, "/events/"+escape(eventID)+"/"+action, http.MethodPost, body, &result, nil)
	return &result, err
}

// GenerateMatchingRun is the resolver for the generateMatchingRun field.
func (r *mutationResolver) GenerateMatchingRun(ctx context.Context, eventID string, idempotencyKey string) (*model.MatchingRun, error) {
	return r.adminMatchingCommand(ctx, "/events/"+escape(eventID)+"/matching-runs", nil, idempotencyKey)
}

// ReviewMatchingRun is the resolver for the reviewMatchingRun field.
func (r *mutationResolver) ReviewMatchingRun(ctx context.Context, runID string, expectedVersion int) (*model.MatchingRun, error) {
	return r.adminMatchingCommand(ctx, "/matching-runs/"+escape(runID)+"/review", map[string]int{"expectedVersion": expectedVersion}, "")
}

// LockMatchingRun is the resolver for the lockMatchingRun field.
func (r *mutationResolver) LockMatchingRun(ctx context.Context, runID string, expectedVersion int, idempotencyKey string) (*model.MatchingRun, error) {
	return r.adminMatchingCommand(ctx, "/matching-runs/"+escape(runID)+"/lock", map[string]int{"expectedVersion": expectedVersion}, idempotencyKey)
}

// PublishMatchingRun is the resolver for the publishMatchingRun field.
func (r *mutationResolver) PublishMatchingRun(ctx context.Context, runID string, expectedVersion int, idempotencyKey string) (*model.MatchingRun, error) {
	return r.adminMatchingCommand(ctx, "/matching-runs/"+escape(runID)+"/publish", map[string]int{"expectedVersion": expectedVersion}, idempotencyKey)
}

// OverridePairing is the resolver for the overridePairing field.
func (r *mutationResolver) OverridePairing(ctx context.Context, runID string, expectedVersion int, input model.PairingOverrideInput, idempotencyKey string) (*model.MatchingRun, error) {
	body := map[string]any{"removeSelectionId": input.RemoveSelectionID, "participantA": input.ParticipantA, "participantB": input.ParticipantB, "reason": input.Reason, "expectedVersion": expectedVersion}
	return r.adminMatchingCommand(ctx, "/matching-runs/"+escape(runID)+"/overrides", body, idempotencyKey)
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*model.Me, error) {
	var result model.Me
	err := r.Upstream.Do(ctx, r.Upstream.Services.Account, "/users/me", http.MethodGet, nil, &result, nil)
	return &result, err
}

// CommunityProfiles is the resolver for the communityProfiles field.
func (r *queryResolver) CommunityProfiles(ctx context.Context, limit *int, cursor *string) (*model.CommunityPage, error) {
	var result model.CommunityPage
	err := r.Upstream.Do(ctx, r.Upstream.Services.Account, "/community/profiles"+query(map[string]string{"limit": intValue(limit, 8), "cursor": stringValue(cursor)}), http.MethodGet, nil, &result, nil)
	return &result, err
}

// CommunityProfile is the resolver for the communityProfile field.
func (r *queryResolver) CommunityProfile(ctx context.Context, profileID string) (*model.CommunityProfile, error) {
	var result model.CommunityProfile
	err := r.Upstream.Do(ctx, r.Upstream.Services.Account, "/community/profiles/"+escape(profileID), http.MethodGet, nil, &result, nil)
	return &result, err
}

// Events is the resolver for the events field.
func (r *queryResolver) Events(ctx context.Context, limit *int, cursor *string) (*model.EventPage, error) {
	var result model.EventPage
	err := r.Upstream.Do(ctx, r.Upstream.Services.Event, "/events"+query(map[string]string{"limit": intValue(limit, 12), "cursor": stringValue(cursor)}), http.MethodGet, nil, &result, nil)
	return &result, err
}

// Event is the resolver for the event field.
func (r *queryResolver) Event(ctx context.Context, eventID string) (*model.Event, error) {
	var result model.Event
	err := r.Upstream.Do(ctx, r.Upstream.Services.Event, "/events/"+escape(eventID), http.MethodGet, nil, &result, nil)
	return &result, err
}

// Bookings is the resolver for the bookings field.
func (r *queryResolver) Bookings(ctx context.Context) (*model.BookingPage, error) {
	var result model.BookingPage
	err := r.Upstream.Do(ctx, r.Upstream.Services.Booking, "/bookings", http.MethodGet, nil, &result, nil)
	return &result, err
}

// Payment is the resolver for the payment field.
func (r *queryResolver) Payment(ctx context.Context, bookingID string) (*model.Payment, error) {
	var result model.Payment
	err := r.Upstream.Do(ctx, r.Upstream.Services.Payment, "/bookings/"+escape(bookingID)+"/payment", http.MethodGet, nil, &result, nil)
	return &result, err
}

// Notifications is the resolver for the notifications field.
func (r *queryResolver) Notifications(ctx context.Context, limit *int, cursor *string) (*model.NotificationPage, error) {
	var result model.NotificationPage
	err := r.Upstream.Do(ctx, r.Upstream.Services.Notification, "/notifications"+query(map[string]string{"limit": intValue(limit, 20), "cursor": stringValue(cursor)}), http.MethodGet, nil, &result, nil)
	return &result, err
}

// UnreadNotificationCount is the resolver for the unreadNotificationCount field.
func (r *queryResolver) UnreadNotificationCount(ctx context.Context) (*model.UnreadCount, error) {
	var result model.UnreadCount
	err := r.Upstream.Do(ctx, r.Upstream.Services.Notification, "/notifications/unread-count", http.MethodGet, nil, &result, nil)
	return &result, err
}

// ManagedEvents is the resolver for the managedEvents field.
func (r *queryResolver) ManagedEvents(ctx context.Context, limit *int) (*model.EventPage, error) {
	if _, err := r.Upstream.RequireAdmin(ctx); err != nil {
		return nil, err
	}
	var result model.EventPage
	err := r.Upstream.Do(ctx, r.Upstream.Services.Event, "/organizer/events"+query(map[string]string{"limit": intValue(limit, 100)}), http.MethodGet, nil, &result, nil)
	return &result, err
}

// MatchingRuns is the resolver for the matchingRuns field.
func (r *queryResolver) MatchingRuns(ctx context.Context, eventID string) (*model.MatchingRunPage, error) {
	if _, err := r.Upstream.RequireAdmin(ctx); err != nil {
		return nil, err
	}
	var result model.MatchingRunPage
	err := r.Upstream.Do(ctx, r.Upstream.Services.Matchmaking, "/events/"+escape(eventID)+"/matching-runs", http.MethodGet, nil, &result, nil)
	return &result, err
}

// MatchingRun is the resolver for the matchingRun field.
func (r *queryResolver) MatchingRun(ctx context.Context, runID string) (*model.MatchingRun, error) {
	if _, err := r.Upstream.RequireAdmin(ctx); err != nil {
		return nil, err
	}
	var result model.MatchingRun
	err := r.Upstream.Do(ctx, r.Upstream.Services.Matchmaking, "/matching-runs/"+escape(runID), http.MethodGet, nil, &result, nil)
	return &result, err
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type (
	mutationResolver struct{ *Resolver }
	queryResolver    struct{ *Resolver }
)
